project:
  type: website
  output-dir: docs
  resources:
    - files/Yiyuan_Li_CV.pdf

website:
  title: "Yiyuan Li"
  site-url: "https://yiyuanli939.github.io/Personal-Website"
  navbar:
    left:
      - href: index.qmd
        text: Home # homepage link 
      - href: blog.qmd 
        text: Blog
  page-footer:
    center: "Â© 2025 Yiyuan Li"

format:
  html:
    theme:
      - cosmo
      - styles.scss 
    toc: true



