project:
  type: website

website:
  title: "Yiyuan Li"
  navbar:
    left:
      - href: index.qmd
        text: Home # homepage link 
      - href: blog.qmd 
        text: Blog

format:
  html:
    theme:
      - cosmo
      - styles.scss 
    toc: true



